baseURL: "https://scottwe.github.io" 
title: Scott Wesley
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Preprints
          url: preprints/
          weight: 3
        - name: Outreach
          url: outreach/
          weight: 4
        - name: Education
          url: education/
          weight: 5
        - name: Service
          url: service/
          weight: 6

params:
    description: "This website documents the research and academic work of Scott Wesley."
    author: Scott Wesley
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers","outreach","service"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Scott Wesley (PhD Student)
          subtitle: "I am a PhD Candidate in the department of Mathematics at Dalhousie University under the supervision of Dr. Neil Julien Ross. My research interests include quantum computing, categorical algebra, computational algebra, and formal methods."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Papers
              url: papers/
            - name: Preprints
              url: preprints/
            - name: Outreach
              url: outreach/
            - name: Education
              url: education/
            - name: Service
              url: service/

    socialIcons:
        - name: Email
          url: mailto:scott.wesley@dal.ca
        - name: cv
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user&user=vLuVbrYAAAAJ
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Scott-Wesley
        - name: GitHub
          url: https://github.com/scottwe
        - name: LinkedIn
          url: https://www.linkedin.com/in/scott-wesley-340966419
        - name: stackoverflow
          url: https://stackoverflow.com/users/6599143/scottwe

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Scott Wesley"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
